### ISSUE TITLE
need   example of llama with flash checkpoint

### ISSUE THREAD

**Issue by yiyuanyu17** [intelligent-machine-learning/dlrover#1029]
hello，we hope a example of  llama with flash checkpoint to test the time of pause training when exporting checkpoints. thanks！

**Comment by workingloong** [comment]
Megatron-LM provides an example to run llama2 in the [llama2.md](https://github.com/NVIDIA/Megatron-LM/blob/main/docs/llama2.md). If you can run the example, you can use flash checkpoint in Megatron-LM by modifying the`megatron/training.py.`

```Python
# from megatron.checkpointing import load_checkpoint
# from megatron.checkpointing import save_checkpoint

from dlrover.trainer.torch.flash_checkpoint.megatron_dist_ckpt import save_checkpoint
from dlrover.trainer.torch.flash_checkpoint.megatron_dist_ckpt import load_checkpoint
```

In addition, we will add an example of llama2 to use flash checkpoint to save the checkpoint of FSDP in the [llama2 example](https://github.com/intelligent-machine-learning/dlrover/blob/master/atorch/examples/llama2/README.md) of ATorch.
