### ISSUE TITLE
The job stops restarting workers and exits if the traceback is a code bug.

### ISSUE THREAD

**Issue by workingloong** [intelligent-machine-learning/dlrover#1068]
The restarted worker will fail again if the training fails due to a code bug. The job should exit as soon as possible to release resources on a cluster.

**Comment by BalaBalaYi** [comment]
A blacklist mechanism can be introduced to this case: throw an explicit error for user code errors with no more retry and free up resources.

**Comment by BalaBalaYi** [comment]
[user_code_bug_demo_log.txt](https://github.com/intelligent-machine-learning/dlrover/files/15089554/user_code_bug_demo_log.txt)
