### ISSUE TITLE
故障自动恢复后，load(flash ckpt)后loss异常震荡

### ISSUE THREAD

**Issue by suenphey** [intelligent-machine-learning/dlrover#1097]
使用dlrover在训练过程中，发生几次故障自动恢复，但是自动load ckpt(flash checkpoint)后的几个iter会发生loss异常震荡
![image](https://github.com/intelligent-machine-learning/dlrover/assets/34848377/22c09b4e-7e17-4eb1-862a-907fdfc31a1f)
上图红色框里面是两次故障重启后的loss，下图为未发生故障重启的loss
![image](https://github.com/intelligent-machine-learning/dlrover/assets/34848377/9f928856-0c33-4e22-98d8-035744769bc7)

**Comment by suenphey** [comment]
补充一下是：megatron框架

**Comment by TomSuen** [comment]
> 补充一下是：megatron框架
您好，请问您是怎么把dlrover和megatron结合起来用的呀？是只用到flash checkpoint功能吗？我的疑惑点在于，官方说dlrover-run只能替换torchrun运行的脚本，难道不能是dlrover-run...deepspeed...的形式吗
