### ISSUE TITLE
kubectl -n dlrover apply -f  examples/pytorch/nanogpt/elastic_job.yaml  error

### ISSUE THREAD

**Issue by yangzhipeng1108** [intelligent-machine-learning/dlrover#1109]
error: resource mapping not found for name: "torch-nanogpt" namespace: "dlrover" from "examples/pytorch/nanogpt/elastic_job.yaml": no matches for kind "ElasticJob" in version "elastic.iml.github.io/v1alpha1"
ensure CRDs are installed first

**Comment by workingloong** [comment]
You should deploy the ElasticJob CRD on your cluster with the [tutorial](https://github.com/intelligent-machine-learning/dlrover/blob/master/docs/tutorial/torch_elasticjob_on_k8s.md#deploy-the-elasticjob-crd-on-the-kubernetes-cluster).
