### ISSUE TITLE
make deploy IMG=easydl/elasticjob-controller:master

### ISSUE THREAD

**Issue by yangzhipeng1108** [intelligent-machine-learning/dlrover#1115]
test -s /root/dlrover/dlrover/go/operator/bin/controller-gen || GOBIN=/root/dlrover/dlrover/go/operator/bin go install sigs.k8s.io/controller-tools/cmd/controller-gen@v0.9.2
go: sigs.k8s.io/controller-tools/cmd/controller-gen@v0.9.2: sigs.k8s.io/controller-tools/cmd/controller-gen@v0.9.2: Get "https://proxy.golang.org/sigs.k8s.io/controller-tools/cmd/controller-gen/@v/v0.9.2.info": dial tcp 172.217.163.49:443: i/o timeout
make: *** [Makefile:127: /root/dlrover/dlrover/go/operator/bin/controller-gen] Error 1

**Comment by workingloong** [comment]
The `make deploy` can not download go modules for the reason that the network is not connected with `sigs.k8s.io`.
