### ISSUE TITLE
possible typo in the example of [tf_elasticjob_on_k8s]

### ISSUE THREAD

**Issue by lichadehehehe** [intelligent-machine-learning/dlrover#1123]
the file of ``` docs/tutorial/tf_elasticjob_on_k8s.md ``` potentially contains typo. 

The steps for creating an auto scaling job is exactly the same as creating a manual scaling job.

<img width="805" alt="image" src="https://github.com/intelligent-machine-learning/dlrover/assets/83261960/3c2d1c68-277d-4e45-a05c-f065e2197044">

**Comment by workingloong** [comment]
Yeah, I have fixed it in #1141
