### ISSUE TITLE
straggler-detection 

### ISSUE THREAD

**Issue by alex337** [intelligent-machine-learning/dlrover#1138]
请问一下对节点分组计算 elapsed time 时是怎么计算的，如果node1和node2一组运行ddp，那这两个节点的 elapsed time 不应该是一样的吗？

**Comment by alex337** [comment]
大佬，两个问题：
1. 每个组内的节点执行 allreduce 时，两个节点之间会通信吗，如果节点之间通信的话两个节点的耗时应该是一样的吧
2. 这种检测可以检测出具体的是慢节点或者故障节点上的哪个网卡有问题吗，看了一下代码好像没有指定网卡的操作
感谢回复

**Comment by alex337** [comment]
大佬，跑了一下example，同一个组内的节点执行 all_gather 的耗时好像是不一样的，这个是因为  all_gather  只是节点内部执行的吗，那节点间通信用的什么呀，感谢解答

**Comment by workingloong** [comment]
应该相差不大吧，完全一样那肯定不可能。你可以用最新的代码跑下，最新的代码改了计时的逻辑。https://github.com/intelligent-machine-learning/dlrover/blob/a9359aa30b0d6f0554f2f809e2cae3e54e1ad342/dlrover/trainer/torch/node_check/utils.py#L88-L111
