### ISSUE TITLE
Why checkpoint can't be copied to shared memory Asynchronously to shared memory when using Flash Checkpoint?

### ISSUE THREAD

**Issue by Reflect0** [intelligent-machine-learning/dlrover#1187]
When using flash checkpoint, I'm wondering why checkpoint can't be copied to shared memory asynchronously to shared memory.  The time can be further reduced if this feature is implemented.

**Comment by workingloong** [comment]
It is a good idea. Synchronous copy is much simpler than async. What's more, the time to copy across nodes is very fast with fast network.
