### ISSUE TITLE
[Error] When using deepspeed to start a megatron training task, only rank 0 of the flash checkpoint saves the model

### ISSUE THREAD

**Issue by liangxuZhang** [intelligent-machine-learning/dlrover#1199]
Thanks for amazing work to accelerate distributed training. When I use 'deepspeed train.py' to start megatron-lm train task, I get this log
![image](https://github.com/user-attachments/assets/61e66463-15c5-4723-8f00-1e9042d47b75)
It seems only rank 0 saved the model weight to shared memory, so when save to disk it's blocked. But when I use dlrover-run to start the training task, the flash checkpoint saves the model weights normally.
![image](https://github.com/user-attachments/assets/c5caa0b7-72f9-4519-88b9-7a3cc310b8ab)

Using Megatron-LM 0.6.0 and dlrover 0.3.6rc0

**Comment by workingloong** [comment]
You can check whether other ranks have the non-empty state dict when calling save_checkpoint.

**Comment by TomSuen** [comment]
您好，请问你只是用了flash checkpoint功能吗？我想知道dlrover-run可以跟deepspeed一起用吗 @liangxuZhang
