### ISSUE TITLE
easydl/elasticjob-controller:master image pull error

### ISSUE THREAD

**Issue by xywangbuaa** [intelligent-machine-learning/dlrover#1222]
I have pulled the docker image to the k8s node. When I start execute the command "make deploy IMG=easydl/elasticjob-controller:master", it occurs an error: 
Failed to pull image "easydl/elasticjob-controller:master": failed to pull and unpack image "docker.io/easydl/elasticjob-controller:master": failed to copy: httpReadSeeker: failed open: unexpected status code https://k888wt7b.mirror.aliyuncs.com/v2/easydl/elasticjob-controller/blobs/sha256:5f80a38cb015768c1f273987f6ac784632f0aac64ddad5bd8a1d2fe9e751df0c?ns=docker.io: 500 Internal Server Error - Server message: unknown: unknown error"
I see the docker image in docker hub is "linux/arm64" architecture, but my architecture is "linux/amd64", does this issus have bad influence?

**Comment by workingloong** [comment]
You can `cd dlrover/go/operator` and `make docker-build docker-push IMG=<some-registry>/operator:tag ` to build the image by yourself. https://github.com/intelligent-machine-learning/dlrover/blob/master/dlrover/go/operator/README.md
