### ISSUE TITLE
dlrover-master被刪除

### ISSUE THREAD

**Issue by zhangQiWorr** [intelligent-machine-learning/dlrover#1342]
请问一下，dlrover-master的pod有容灾策略吗，如果dlrover-master所在主机挂了，dlrover-master下下相关的训练任务是不是会挂掉？

**Comment by BalaBalaYi** [comment]
Yes. The master's fault-tolerance is not supported by the community version for now. We will consider how to give out a solution for community version to support master fault-tolerance.
