### ISSUE TITLE
How about migrating the tfplus and atorch as independent repositories?

### ISSUE THREAD

**Issue by mingcheng** [intelligent-machine-learning/dlrover#1358]
FYI, I think the two libraries at the root of the project are very independent and transferable.

**Comment by antfin-oss** [comment]
This is a huge PR #1359; it must be reviewed and confirmed before merging.

**Comment by antfin-oss** [comment]
> This is a huge PR #1359; it must be reviewed and confirmed before merging.

I closed this pull request because it didn't pass the CI test. You can open PR again if everything is ready.

**Comment by mingcheng** [comment]
> > This is a huge PR #1359; it must be reviewed and confirmed before merging.
> 
> I closed this pull request because it didn't pass the CI test. You can open PR again if everything is ready.

Generated the new pull request and passed the CI test. so it's ready to merge #1360
