### ISSUE TITLE
Flash Checkpoint incomplete saving

### ISSUE THREAD

**Issue by xuLn-0813** [intelligent-machine-learning/dlrover#1378]
**Describe the bug**
First of all, thank you for your work. During the verification and usage process, I encountered an issue when using Flash Checkpoint. When the last checkpoint  is being saved asynchronously during training, there is a problem with incomplete saving.

I have initially investigated the cause, and it appears that the training process has already completed, the main process exiting, which in turn causes the child process responsible for saving the checkpoint to exit as well, resulting in this situation.Do you have any similar findings?

**APP Info (please complete the following information):**
 - DLRover: 0.3.7

**HARDWARE Info (please complete the following information):**
 - Device: GPU A100

**Comment by workingloong** [comment]
Yes. We will implement a method to wait the latest checkpoint persistence. Now, you can use `time.sleep` to wait the persistence process to walk around the issue.

**Comment by xuLn-0813** [comment]
> Yes. We will implement a method to wait the latest checkpoint persistence. Now, you can use `time.sleep` to wait the persistence process to walk around the issue.

I saw #1380. I have an idea, is it possible to convert the last save to synchronization?

**Comment by workingloong** [comment]
> > Yes. We will implement a method to wait the latest checkpoint persistence. Now, you can use `time.sleep` to wait the persistence process to walk around the issue.
> 
> I saw #1380. I have an idea, is it possible to convert the last save to synchronization?

Yeah，you can call `torch.save` or other APIs to synchronously save the checkpoint at the end of training loop.
