### ISSUE TITLE
ElasticTrainer monitors the speed of PyTorch  training.

### ISSUE THREAD

**Issue by workingloong** [intelligent-machine-learning/dlrover#337]
`ElasticTrainer` need to sample the training speed.  We can search for the optimal number of workers to speed up the training with the speed.

**Comment by IRONICBo** [comment]
@workingloong Hello, For this task[https://summer-ospp.ac.cn/org/prodetail/233dd0048?list=org&navpage=org], the main idea of my implementation is as follows:

First, in the `_periodic_adjust_worker` method of `dlrover/python/master/node/job_auto_scaler.py:AllreduceTrainingAutoScaler`, the current practice is to check the number of available workers at regular intervals and And add to the training queue, you need to add some monitoring metrics, add some monitoring information and monitoring functions.

In `LocalOptimizer` or `BrainResoureOptimizer`, the metrics are calculated based on the monitored data. Similar to the core functions `_generate_worker_resoruce` and `_compute_worker_speed_ratio` inside the PS architecture. In the AllReduce approach, a combination of communication time, throughput, and locally optimal batch size is required.

I need to package dlrover as a docker image and then verify my algorithm in k8s is correct. Is there a mature way of debugging the dlrover framework that you can suggest?

**Comment by workingloong** [comment]
We have implemented it in #681
