### ISSUE TITLE
An example to support nanoGPT.

### ISSUE THREAD

**Issue by workingloong** [intelligent-machine-learning/dlrover#439]
[nanoGPT](https://github.com/karpathy/nanoGPT) is the simplest, fastest repository for training/finetuning medium-sized GPTs. We can use nanoGPT to test fault-tolerance and elasticity of DLRover.

**Comment by merlintang** [comment]
+1

**Comment by yzlnew** [comment]
Maybe consider [nanoGPT](https://github.com/karpathy/nanoGPT)?

**Comment by Antlera** [comment]
Add the example to support nanoGPT by #516 .
