### ISSUE TITLE
Add GPU Resources Monitoring.

### ISSUE THREAD

**Issue by Antlera** [intelligent-machine-learning/dlrover#546]
This issue aims to implement the ability to monitor the GPU resources such as GPU utilization and GPU memory usage during the model training. This feature is crucial for our adaptive model trainer as it will provide the base metrics we need to optimize the batch size. The implementation should be carried out in the `dlrover/python/elastic_agent/monitor/resource.py` file. We will need to identify the best ways to integrate GPU monitoring into our trainer and the metrics that we should be tracking.

**Comment by workingloong** [comment]
The issue has been implemented in #611.
