### ISSUE TITLE
Roadmap for the dlrover

### ISSUE THREAD

**Issue by merlintang** [intelligent-machine-learning/dlrover#575]
Dear All

do we have a production release plan recently? we can start the discussion  here. 

thanks 

Mike

**Comment by workingloong** [comment]
Released:
v0.1.0:  TensorFlow PS training: elasticity, fault-tolerance, and resource auto-configuration on Kubernetes and Ray.
v0.2.0: PyTorch training: elasticity, fault-tolerance of PyTorch distributed training on Kubernetes.

Planning:
v0.3.0: Dynamic optimization of distributed training on a single node or a Kubernetes cluster. The optimization includes:
- Dynamically adjust the batch size to improve the throughput.
- Dynamically adjust the strategy of FSDP to improve the throughput.
- ...

**Comment by merlintang** [comment]
thanks for leave the road map for this.
