### ISSUE TITLE
When using FSDP on the nanoGPT model, the loss does not decrease.

### ISSUE THREAD

**Issue by xin-chen42** [intelligent-machine-learning/dlrover#584]
When using FSDP on the nanoGPT model, the loss does not decrease but rather bounces around the initial value.It is possible that the parameters are not being updated.
![image](https://github.com/intelligent-machine-learning/dlrover/assets/117803100/97e4a040-f2a7-479a-82b7-1523ed9528d4)
![image](https://github.com/intelligent-machine-learning/dlrover/assets/117803100/76c5b824-e219-4fc3-8f9f-28f6455d4180)

**Comment by Antlera** [comment]
Closed as fixed by #585 .
