### ISSUE TITLE
[Example] Add alpaca-lora peft support example.

### ISSUE THREAD

**Issue by Antlera** [intelligent-machine-learning/dlrover#656]
We need to support alpaca-lora finetune. This would be a best practice for users to optimize Parameter-Efficient Fine-Tuning (PEFT) job with dlrover.

**Comment by Antlera** [comment]
Repo link for alpaca-lora : https://github.com/tloen/alpaca-lora

**Comment by matmua** [comment]
Tengda Guo

**Comment by workingloong** [comment]
The example has been added in #782
