### ISSUE TITLE
Create paral_config from json file.

### ISSUE THREAD

**Issue by Antlera** [intelligent-machine-learning/dlrover#700]
The [config tuner](https://github.com/intelligent-machine-learning/dlrover/blob/master/dlrover/python/elastic_agent/config/paral_config_tuner.py#L80) tries to read JSON file and create paral config in a fixed style. However, we may update the paral_config structure and content later. We need a method to read it flexibly.

**Comment by Antlera** [comment]
@matmua

**Comment by matmua** [comment]
Got
