### ISSUE TITLE
新需求Issue：作业Worker POD启动后网络异常, 超过一定时间（比如15min）还没有发送ready 信息，master 就把这个 Pod 主动kill掉, 重新拉起一个POD。

### ISSUE THREAD

**Issue by cooper190113** [intelligent-machine-learning/dlrover#724]
1、作业Worker POD启动后网络异常, 超过一定时间（比如15min）还没有发送ready 信息，master 就把这个 Pod 主动kill掉, 重新拉起一个POD。
2、此场景可以通过参数控制，不开启时按照当前流程重新组网缩容，开启时可以主动kill掉pod，重新拉起一个。

**Comment by workingloong** [comment]
我通过 chaos 将worker-0 网络的丢包率设置为100%，命令如下：`./blade create network loss --percent 100 --interface eth0`
worker 会因为网络连接失败自动报错。如果 worker 自动报错，如果配置了 restartPolicy: Always， 那么edl 会自动重启 worker-0 的。
![image](https://github.com/intelligent-machine-learning/dlrover/assets/18071380/e00d82f9-5bf9-4a74-b8a6-c9ecd49ecd80)
