### ISSUE TITLE
对于huggingface  Accelerate 和 trainer 库编写的任务，也可以直接支持嘛？

### ISSUE THREAD

**Issue by qiankunli** [intelligent-machine-learning/dlrover#763]

**Comment by workingloong** [comment]
支持的，只要是能用 torchrun 启动的任务，都是支持用 dlrover-run 来跑的。dlrover-run 是扩展了torchrun，所以原生的torchrun的配置都支持。

**Comment by workingloong** [comment]
我们提供了一个使用 huggingface trainer 来微调  llama2 的例子 https://github.com/intelligent-machine-learning/dlrover/tree/master/examples/pytorch/llama2
