### ISSUE TITLE
使用了tfplus的模型推理的时候怎么使用？

### ISSUE THREAD

**Issue by supercocoa** [intelligent-machine-learning/dlrover#777]
有对应的tensorflow-serving或者triton版本吗

**Comment by Wlong692** [comment]
非常抱歉，目前TFPlus还没有集成tensorflow-serving或者triton的版本，但是你可以通过将TFPlus的算子加入到您使用的推理后端，然后重新编译来实现这个目的。
后续我们会发布一个推理支持文档来详细说明如何支持模型推理框架。

**Comment by supercocoa** [comment]
最好能像阿里的deeprec或者英伟达的hugectr一样提供训练+推理一整套方案，不然没法用呀 @Wlong692 
https://github.com/DeepRec-AI/DeepRec
https://github.com/NVIDIA-Merlin/HugeCTR

**Comment by Wlong692** [comment]
感谢建议，我们有支持tensorflow-serving的计划，根据排期进度，预计将会在下个版本中提供一个支持tensorflow-serving的方案。目前由于TFPlus只支持CPU，所以暂时没有支持triton的计划。

**Comment by supercocoa** [comment]
看最新的tfplus还支持了flash-attention，这个必须得跑到gpu上吧？那这个用triton做serving是不是好点？ @Wlong692

**Comment by mars1248** [comment]
是的，只支持sm75,80,90+。导出时用原来的方式即可，目前flash attention还只支持训练
