### ISSUE TITLE
Does DLRover have plan to support the MindSpore backend framework?

### ISSUE THREAD

**Issue by botieking98** [intelligent-machine-learning/dlrover#888]

**Comment by workingloong** [comment]
Now, we are developing features to support running `torch_npu` on Ascend 910 processor. If you have any ideas and solutions to support Mindspore, feel free to submit PRs.

**Comment by superleo** [comment]
> Now, we are developing features to support running `torch_npu` on Ascend 910 processor. If you have any ideas and solutions to support Mindspore, feel free to submit PRs.

do we have design doc for that? or a guide/doc for us to implement a new processor support in dlrover.

**Comment by workingloong** [comment]
Yeah, we are writing the guide and designing the APIs to use DLRover with new AI chips. We can discuss the detail of API design together if you are interested in implementing a new processor support in dlrover.

**Comment by workingloong** [comment]
I have submitted a PR in #1026 to show how to implement a new processor support in DLRover.
