### ISSUE TITLE
Discussion: how to name the APIs to async save/load checkpoints.

### ISSUE THREAD

**Issue by workingloong** [intelligent-machine-learning/dlrover#896]
We are developing the features to asynchronously save the checkpoint into the storage and provide APIs to users.  Now, there are two schemes to name the APIs. We can select one scheme or offer a new scheme. Please vote your scheme in replies.

Scheme 1:
```
def save_checkpoint_to_memory():
    """ Synchronously save the checkpoint to the CPU memory."""
    pass

def save_checkpoint_to_storage():
    """ Asynchronously save the checkpoint to the storage."""
    pass

def load_checkpoint():
    """ 
    Load the checkpoint from the CPU memory if the state dict is in the memory.
    Otherwise, load the checkpoint from the storage.
    """
    pass
```

Scheme 2:
```
def save_checkpoint(in_memory=True/storage_level="memory_only/disk"):
    """ 
    If to_memory, synchronously save the checkpoint to the CPU memory.
    Otherwise, asynchronously save the checkpoint to the storage.
    """
    pass

def load_checkpoint():
    """ 
    Load the checkpoint from the CPU memory if the state dict is in the memory.
    Otherwise, load the checkpoint from the storage.
    """
    pass

```

**Comment by merlintang** [comment]
I perfer schem2 like the spark rdd operation (https://spark.apache.org/docs/latest/api/python/reference/api/pyspark.RDD.persist.html) :)

**Comment by yezhem** [comment]
I prefer scheme 1
From "code smells": It is best not to use flag/boolean types as function parameters. Flags are not a best practice because they reduce the cohesion of a function. It does more than one thing making it hard to understand what a function does based on the call site.
If I want to modify the checkpoint storage mode, for scheme 1, I can simply replace the function name directly. For scheme 2, I may need to adjust the parameters, which may not be as straightforward.

**Comment by workingloong** [comment]
> I perfer schem2 like the spark rdd operation (https://spark.apache.org/docs/latest/api/python/reference/api/pyspark.RDD.persist.html) :)

The RDD scheme is similar to the scheme 2 and I have updated the scheme 2.

**Comment by samplise** [comment]
I prefer scheme 2 since it hides details from users. Moreover, we should provide a reasonable default setup when users do not provide any configuration.

**Comment by nash635** [comment]
scheme 2
+1

**Comment by Antlera** [comment]
I prefer scheme 2 since it looks more like a unified interface. When users do not specify which place to checkpoint their models, we make the choices for users to achieve higher performance **by default**.
