### ISSUE TITLE
Does tfplus/kv_variable support TF2？

### ISSUE THREAD

**Issue by fuhailin** [intelligent-machine-learning/dlrover#938]

**Comment by Wlong692** [comment]
Thank you for reaching out with your question about `tfplus/kv_variable` compatibility with TensorFlow 2 (TF2).

In brief, while `TFPlus` is developed with support for TF2 (specifically, TensorFlow 2.13.0), it currently utilizes TensorFlow 1 (TF1) compatibility interfaces for certain functionalities, including training. This means our full support for TF2 features, especially the default Eager Execution mode, is still in progress.

For training, `TFPlus` currently supports CPU-only environments and has been tested on Linux platforms. We are planning to expand this support in future versions.

For detailed information and future updates, please refer to our documentation:
- [Readme](https://github.com/intelligent-machine-learning/dlrover/blob/master/tfplus/README.md)
- [Tutorials](https://github.com/intelligent-machine-learning/dlrover/blob/master/tfplus/docs/tutorials.md)

We appreciate your interest in `TFPlus` and are working towards full TF2 feature support.
