### ISSUE TITLE
pip install dlrover[torch] -U ERROR：Failed building wheel for grpcio-tools

### ISSUE THREAD

**Issue by chencjcj** [intelligent-machine-learning/dlrover#970]
When I execute "pip install dlrover[torch] -U," an error occurs.      
error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for grpcio-tools
  Running setup.py clean for grpcio-tools
Failed to build grpcio-tools
ERROR: Could not build wheels for grpcio-tools, which is required to install pyproject.toml-based projects

**Comment by workingloong** [comment]
You can try Python38 and I have submitted the  PR #950 update grpc-tools version in the deps

**Comment by workingloong** [comment]
You can retry to `pip install dlrover[torch]==0.3.2 -U`
