### ISSUE TITLE
DdpCheckpointer does not support Huawei ascendspeed

### ISSUE THREAD

**Issue by wangw-david** [intelligent-machine-learning/dlrover#975]
I used Huawei ascendspeed to divide the model into 8 npu, and then used DdpCheckpointer to save the checkpoint file, but only the file was saved on npu0. 
I look forward to supporting ascendspeed+ddp.

**Comment by workingloong** [comment]
We have released dlrover-0.3.3 and you can retry it by pip install dlroverl[torch]==0.3.3 -U. You can set local_shard_num=$nproc_per_node in the DdpCheckpointer to asynchronously save the checkpoint of ascend DDP.
